---
- hosts: maptaxonomy
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: create nginx config file link
      file:
        src: '/srv/www/maptaxonomy/site/maptaxonomy/map_taxonomy_nginx.conf'
        dest: '/etc/nginx/sites-enabled/map_taxonomy_nginx.conf'
        state: link
    - name: start supervisord
      service:
          name: supervisord
          state: started
          args: '-c /srv/www/maptaxonomy/site/maptaxonomy/supervisor.conf'
    - name: update supervisor
      supervisorctl: name=uwsgi-runner state=restarted
    - name: restart nginx
      service:
          name: nginx
          state: restarted